name: update-stylesheet

on:
  workflow_dispatch:
  # Scheduled trigger
  schedule:
    - cron: '42 0 * * *'
   
jobs:
  download-stylesheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make script executable
        run: chmod +x indent.sh
      
      - name: Make temporary directory
        run: mkdir temp

      - name: Download CSS file
        run: |
          sheets=$(curl --list-only https://discord.com/app | grep -o "<[^<>]*stylesheet[^<>]*\/>" | cut -d " " -f2 | cut -d \" -f2)
          for i in $sheets; do
            wget -O - > temp/$(basename $i) "discord.com$i"
          done
          
      - name: Format stylesheets
        run: |
          for i in temp/*.css; do
            sed 's/\([}{]\)/\n\1\n/g' $i | sed 's/\(;\)/\1\n/g' | ./indent.sh > $(basename $i | cut -d "." -f1).css
          done
        
      - name: Clean up files
        run: rm -r ./temp
        
      - name: Check for errors
        run: |
          for i in ./*.css; do
            test -s $i
          done
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.css'
          commit_author: GitHub actions <actions@github.com>
