name: update-stylesheet

on:
  workflow_dispatch:
  # Scheduled trigger
  schedule:
    - cron: '42 0 * * *'
   
jobs:
  download-stylesheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make script executable
        run: chmod +x indent.sh
      
      - name: Download CSS file
        run: |
          wget -O temp.css discord.com/$(curl --list-only https://discord.com/app | grep -o "<[^<>]*stylesheet[^<>]*\/>" | cut -d " " -f2 | cut -d \" -f2)
          
      - name: Format stylesheet
        run: cat temp.css | sed 's/\([}{]\)/\n\1\n/g' | sed 's/\(;\)/\1\n/g' | ./indent.sh > stylesheet.css
        
      - name: Clean up files
        run: rm temp.css
        
      - name: Check for errors
        run: test -s stylesheet.css
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: stylesheet.css
          commit_author: GitHub actions <actions@github.com>
